### ISSUE TITLE
Use of local facts

### ISSUE THREAD

**Issue by ganto** [debops/debops-policy#16]
Quote from the DebOps Code Standards Policy:

> roles SHOULD use Ansible local facts stored on the hosts to keep their internal state consistent and idempotent at all times, no matter if the role is used standalone or a part of another role’s playbook. The facts can be either static or dynamically generated, or a combination of the two.

In the past few months I tried to write some more complicated rules (e.g. [debops-contrib.checkmk_server](https://github.com/debops-contrib/ansible-checkmk_server)) and also now, I try to implement a more complicated feature (cluster bootstrapping support) to the [debops.mariadb_server](https://github.com/debops/ansible-mariadb_server) role and I somehow feel, that I still haven't created a good understanding of Ansible local facts and how they should be properly used in DebOps.

About Ansible local facts I understood so far, that they help to report state on a server:
1. To other roles on the same server
1. To a role itself over multiple playbook runs
1. To other roles on other servers if they are part of the same playbook execution
1. To a central facts database (e.g. CMDB)

**Case study: mariadb_server**
Now I was trying to figure out, how `debops.mariadb_server` is using local facts. I just picked this role because I was working on it. The following things appeared to me:

- The local facts are set and (re-read) as last task in the role. There is a reference to `ansible_local.mariadb.flavor` in the `defaults/main.yml` when defining `mariadb_server__flavour` which means if a server is installed on a host that previously acted as a client, it will automatically pick-up the flavor of the client. Don't know if this is really intended...
- Other than that, there are no more references except in the facts template `mariadb.fact.j2`
- The facts template only fills in the current role configuration if it cannot find any previous facts of this role. E.g.:
```
{% set mariadb__tpl_client      = ansible_local.mariadb.client      if (ansible_local|d() and ansible_local.mariadb|d() and ansible_local.mariadb.client|d())      else "localhost" %}
...
{
"client": "{{ mariadb__tpl_client }}",
...
}
```
There are various (intended?) side effects of this definitions:
- If variable values which are persisted as local facts are changed via Ansible inventory, they are used correctly by the role itself (with exception of `mariadb_server__flavour`, see above), but the facts are never updated. The facts file has to be deleted manually so that the template would fill-in the new values afterwards. I guess _this needs some documentation_ in the `defaults/main.yml` next to the affected variables. 
- If the host has been used as client before, there is already a `mariadb` fact file, which will never get updated with any new server "facts".

**Case study: mariadb**
Let's check if I understand how these facts interact with the client role. That might run on the same host (after the `mariadb_server` role) or on another host.

- Here the facts are not set last. After setting the facts, there is still a task group for managing database content afterwards. However, those tasks never access `ansible_local.mariadb` facts but get all their data directly from the inventory or registered variables. 
- Also here, the facts are only used for setting the flavor `mariadb__flavor` and for making sure the facts template (`mariadb.fact.j2`) fills the same content for consecutive role execution.
- Interesting to see, that the server and client roles are using the same facts dictionary.

Let's see if I can understand why we need facts here:

- On a fresh host, the installation of `mariadb_server` will create a facts file such as:
```
{
"client": "localhost",
"delegate_to": "",
"flavor": "mariadb",
"host": "localhost",
"port": "3306",
"server": "localhost"
}
```
* The client role however doesn't check the `mariadb` facts, but decides by itself, that if no `mariadb__server` is defined, it should fallback to `'localhost'`. If the server runs on a non-default port, the user has to manually specify the port as client inventory variable, even the facts would already provide the correct value from the server.

**Other roles**
There are some references in other roles to the `mariadb` facts. Finally some examples for point **(1)** above. E.g.: 
* In `debops.etherpad` where the database server is read from the facts to later configure the application accordingly:
```
etherpad_database_server: '{{ ansible_local.mariadb.server
                              if (ansible_local|d() and ansible_local.mariadb|d() and
                                  ansible_local.mariadb.server|d())
                              else "" }}'
```
* In `debops.librenms` where a database is created on the database server found in the facts:
```
- name: Create LibreNMS database
  mysql_db:
    name: '{{ librenms__database_name }}'
    state: 'present'
  delegate_to: '{{ ansible_local.mariadb.delegate_to }}'
```

**Summary**
I'm not sure if the facts are correctly used in this example. The only use I found from my understanding is those facts provide information to other roles. 
But the policy says something else, so I wish to understand what threatens this consistency and idempotency mentioned in the policy when you don't use facts. Maybe can someone give an example?

**Comment by drybjed** [comment]
First of all, that particular policy is meant to discourage use variables of other roles directly in your own role to pass the data around. This method is certainly possible in Ansible, but it can lead to errors when a particular role is not in the current play - for example, `debops.mariadb` role can be used either standalone in its own playbook, or as a dependent role in some other playbook, with different values each time. Local facts are meant to provide consistent communication channel between roles regardless of wether they are included in the playbook or not.

I don't want this to be an absolute rule, don't think that you have to create local facts in all of your roles. But, if you plan to exchange data between roles, this is the method I suggest you should use.

The facts in the `debops.mariadb` and `debops.mariadb_server` roles were written some time ago. At present time, I would write them as a Python script and probably make them more dynamic, for example to check if values defined in the inventory/defaults need to be updated. In the past I used facts as static information set in stone, but that is changing recently.

Roles use the same `ansible_local.mariadb.*` set of facts, because these facts are meant more for other roles than the MariaDB roles. Therefore for consistency (since other roles will look for all the relevant information under `ansible_local.mariadb.*`), both role configure a similar set of facts. The `debops.mariadb_server` will override some facts if its installed after `debops.mariadb`, but the idea is to keep the environment the same for the sake of other applications that might use MariaDB on the same or another host. I admit that some default variables could be templated from local facts (for example `mariadb__port`, maybe) but after a review probably most would stay the same. 

In summary, `ansible_local.mariadb.*` facts exist so that your application role can use them without a requirement to set the MariaDB server statically in its own default variables. if you use the example task provided in `debops.mariadb` documentation with the role itself, your application should be able to connect to the database no matter if its on the same host, or another host. Thats the only function these particular facts provide.

I think that using facts from other roles as a base is the wrong approach, this issue should be solved on a case by case basis. For example, [debops.redis](https://github.com/debops/ansible-redis) has [very extensive fact script](https://github.com/debops/ansible-redis/blob/master/templates/etc/ansible/facts.d/redis.fact.j2) which is meant both to provide needed configuration parameters to other roles, and to keep the `debops.redis` internal state consistent. In the end, what facts you expose to your or other roles depends only on that role function. Some roles don't need local facts at all, some do. My advice would be to write your role as normal, and when you feel that you need local facts for something, go for them. You don't need to force them. :-)

**Comment by ganto** [comment]
> First of all, that particular policy is meant to discourage use variables of other roles directly in your own role to pass the data around. This method is certainly possible in Ansible, but it can lead to errors when a particular role is not in the current play

I see. So to make this more illustrative and go back to the mentioned examples, instead of...

```
- name: Create LibreNMS database
  mysql_db:
    name: '{{ librenms__database_name }}'
    state: 'present'
  delegate_to: '{{ mariadb__delegate_to }}'
```

... one should write:

```
- name: Create LibreNMS database
  mysql_db:
    name: '{{ librenms__database_name }}'
    state: 'present'
  delegate_to: '{{ ansible_local.mariadb.delegate_to }}'
```

This makes sense to me, but I guess this can be described a bit simpler. If I understand your explanation and examples correctly, the policy so far "should" only refer to the use of facts for passing configuration states between roles. I'll send a PR for a suggestion.

The "internal state" topic should be (if at all) mentioned separately. I didn't understand this phrase from the policy yet. I'll definitely have a look at the `debops.redis` role as you mentioned. Thanks for the hint.

Whereas variables are documented extensively, I feel that the policy should also request that facts must be documented somewhere as they provide an interface for other roles to depend on which should be well-defined. Not sure yet, where this could be done best. I would suggest to add a separate page in the documentation (e.g. `docs/facts.rst`) but as we already have some issues building the extensive documentation maybe someone else has a better idea?

> The facts in the debops.mariadb and debops.mariadb_server roles were written some time ago.

All the "special" issues with the `mariadb` facts are therefore rather relicts than truly intended design choices. I'll therefore check if I can do some cleanup and maybe I also learn a bit more about the dos and don'ts using facts.

> My advice would be to write your role as normal, and when you feel that you need local facts for something, go for them. You don't need to force them. :-)

Sure, my thoughts are more in the direction of where to set the limit? As I mentioned before in https://github.com/debops/ansible-mariadb_server/pull/36#issuecomment-259897262, I see some use cases that would rely heavily on facts to detect configuration states. E.g. something in the sense of:

```
mariadb_server__wsrep_cluster_address: 'gcomm://{{
  groups[mariadb_server__cluster_inventory_group] | 
  map('extract', hostvars, ["ansible_local", "mariadb_server", "wsrep_node_address"]) | 
  list | join(",") }}'
```

But from your reaction, I already feel, that this is probably not something you want to see... :smirk:

**Comment by drybjed** [comment]
You are right about usage of `mariadb__delegate_to` in LibreNMS role, although I would define a default variable like:

``` yaml
librenms__database_delegate_to: '{{ ansible_local.mariadb.delegate_to
                                    if (ansible_local|d() and ansible_local.mariadb|d() and
                                        ansible_local.mariadb.delegate_to|d())
                                    else ansible_fqdn }}'
```

It's done because this way the final decision what to use for delegation is left to the user. If the `delegate_to` parameter is defined in the `tasks/` files, users cannot modify them if they need to without breaking the DebOps update mechanism. I have no idea if the `delegate_to` would need to be defined by the user, but there might be some environments where that might be handy.

I agree that better documentation about facts is useful, for example `debops.pki` role has them documented. Although I think that should only really apply to facts that are expected to be consumed by other roles - some local facts are left for internal role use only, for example `debops.unattended_upgrades` uses local facts to remember what packages were blacklisted by other roles via dependent variables. Other roles shouldn't mess with these facts directly in this case.

My aversion about `hostvars` usage in examples like yours is that Ansible doesn't really have a good way to enforce some hosts to always be included in facts. Yes, there's a `add_host` module, but I don't think it's a good solution for a general-purpose environment like DebOps; it's very situational. And when you run some clustered role on all hosts in the cluster, I suspect that if you run it next time on just 1 of the cluster elements, you would expect the cluster to not break as a result.

Ansible can keep a fact cache, but from my experience in the past this function is very unreliable and prone to errors. In that case I think that external fact/variable source like `etcd`, `consul` or similar solution which could be accessed at will by Ansible, preferably remotely so that the Ansible Controller wouldn't need to become a part of the environment, would be best. Other CM tools have their own solutions: hiera, Salt Mine, whatever Chef has... I guess Ansible either won't ever have its own tool we could rely on. Perhaps `redis` used as a cache, but I wonder if Ansible can use it remotely over TLS? That would be interesting.
